language: java

sudo: false # faster builds

install: true

jdk:
  - openjdk8

notifications:
  email: false

cache:
  directories:
    - '$HOME/.m2/repository'

script: 
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn cobertura:cobertura -DskipTests=true -Dmaven.javadoc.skip.true

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 6f46f298-6030-476d-8ff1-0fac047342b0
