language: java

jdk:
  - oraclejdk7

script: "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"

notifications:
  email: false

cache:
  directories:
    - '$HOME/.m2/repository'
